export const config = {
    TWITTER_BEARER_TOKEN: process.env.REACT_APP_TWITTER_BEARER_TOKEN || 'AAAAAAAAAAAAAAAAAAAAAOn8ygEAAAAAfyamTI8bc6bTHfxUVt6aiEIv9bw%3DLo4n0LTPKwOnGJKMijPCS2oPWE13ObAS5dbRRMsEmIz27jdy26',
  };